#!/bin/sh

# scripts/build: Build the application

set -ev

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Building…"

./gradlew :shared:assembleXCFramework

bundle exec fastlane build_test_version
