#!/bin/sh

# scripts/build: Build the application

set -evo pipefail

cd "$(dirname "$0")/.."

# Verify repo is clean
if [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit, working tree clean" ]]; then
  echo "Working directory dirty. Please revert or commit."
  exit 1
fi

[ -z "$DEBUG" ] || set -x

# Start publishing
echo "==> Publishing App for ${BUILD_TYPE}…"

./gradlew :shared:assembleXCFramework

bundle exec fastlane publish
